 #Enable the Spark reporter
extent.reporter.html.start=true
extent.reporter.spark.start=true
#Define the output path for the HTML report
extent.reporter.spark.out=reports/extent_report.html
#Screenshot configuration
screenshot.dir=reports/screenshots/
screenshot.rel.path=../screenshots/